### ISSUE TITLE
CC65

### ISSUE THREAD

**Issue by valdirSalgueiro** [bbbradsmith/huffmunch#3] opened 2020-05-21 02:04 UTC
Hi, first of all great library:) Is there any sample how to use this with cc65?(c compiler not library). Probably need a couple exports but im not very versed in asm.

Thanks!

**Comment by bbbradsmith** [comment] 2020-05-21 03:25
danger/test contains a C project I used for testing, there's a small assembly wrapper in test.s that makes the huffmunch decompression library available to the test program (test.c)

I'll consider moving that wrapper to the root, though, to make integration with C programs easier

**Comment by bbbradsmith** [comment] 2020-05-21 08:19
Hmm, not sure if I can really make an easy C integration. The problem is that it needs an allocation on the zero page, and the default CFG for most platforms restrict the size of their ZP segment, so you couldn't actually use it without at least a hand-created CFG.

Hmm, maybe I could have the C implementation temporarily copy the ZP variables over the built-in C ones, but it would add significant performance overhead... :( Well, maybe I can do that but with a note in the source about how to make it better with a custom CFG.

**Comment by bbbradsmith** [comment] 2020-05-21 09:42
I've created the wrapper described. The test program again provides an example of how to use it. Please let me know what you think.

Should work even without a custom CFG. The performance was only 20% worse in the end, but I left an option to override it manually and get that performance back.

(Self reminder: bump version to 1.5 and tag a new release when closing this.)

**Comment by valdirSalgueiro** [comment] 2020-05-25 13:54
wow that was fast :D

will give a try asap!

**Comment by bbbradsmith** [comment] 2023-07-06 01:11
Have finally released 1.5 which includes the C wrapper.

**Closed as completed by bbbradsmith** 2023-07-06 01:11 UTC
